apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
data:
  nginx.config: cGlkIC92YXIvcnVuL25naW54LnBpZDsKCmV2ZW50cyB7CiAgICB3b3JrZXJfY29ubmVjdGlvbnMgMzsKfQoKaHR0cCB7CiAgICBzZXJ2ZXIgewogICAgICAgIHJvb3QgL3Vzci9zaGFyZS9uZ2lueC9odG1sOwogICAgfQp9Cg==
  nginx.html: PCFET0NUWVBFIGh0bWw+CjxodG1sPgogICAgPGhlYWQ+CiAgICAgICAgPHRpdGxlPldlbGNvbWUgdG8gbmdpbnghPC90aXRsZT4KICAgIDwvaGVhZD4KICAgIDxib2R5PgogICAgICAgIDxoMT5OZ2lueCBIb21lIFBhZ2UgZm9yIENvbmZpZ01hcCE8L2gxPgogICAgICAgIDxwPlRoaXMgcGFnZSBpcyBuZ2lueCBwYWdlIGZvciBzYW1wbGUgb2YgQ29uZmlnTWFwLjwvcD4KICAgICAgICA8cD5NeSBQcm9maWxlPC9wPgogICAgICAgIDxwPjxhIGhyZWY9Imh0dHBzOi8vZ2l0aHViLmNvbS90YW1hZ28wMjI0Ij5NeSBHaXRodWI8L2E+PC9wPgogICAgICAgIDxwPjxhIGhyZWY9Imh0dHBzOi8vdHdpdHRlci5jb20vdGFtYWdvXzAyMjQiPk15IFR3aXR0ZXI8L2E+PC9wPgogICAgPC9ib2R5Pgo8L2h0bWw+Cg==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-sample-pod
  labels:
    app: secret-sample-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    volumeMounts:
    - name: nginx-config
      mountPath: "/etc/nginx"
      readOnly: true
    - name: nginx-data
      mountPath: "/usr/share/nginx/html"
      readOnly: true
  volumes:
  - name: nginx-config
    secret:
      secretName: secret-sample
      items:
      - key: nginx.config
        path: nginx.conf
  - name: nginx-data
    secret:
      secretName: secret-sample
      items:
      - key: nginx.html
        path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: secret-service-nginx
spec:
  selector:
    app: secret-sample-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
