apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-app
    name: nginx
  name: nginx-html
data:
  index.html: |
    <html>
      <head>
        <title>
        Kubernetes Hello World
        </title>
      </head>
      <body>
        <h1>
        Kubernetes Hello World
        </h1>
        <h2>
        Kubernetes Nginx ConfigMap
        </h2>
      </body>
    </html>
