apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  ports:
  - name: node-port
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30001
  selector:
    app: nginx-dep
