apiVersion: v1
kind: Service
metadata:
  name: external-ip
spec:
  type: ClusterIP
  externalIPs:
  - 10.20.30.20
  ports:
  - name: cluster-port
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: nginx-dep
