apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: centos
    image: centos:latest
    command:
    - sh
    - -c
    args:
    - for i in 1 2 3 4 5 ; do curl -s http://10.96.67.133:8080 ; sleep 5; done ;exit 0
